### ISSUE TITLE
Creation Date

### ISSUE THREAD

**Issue by moriel5** [maltaisn/another-notes-app#1]
Hello, I am coming over from `Notally`, since there are a few design (mainly related to usability) choices that I do not really prefer over there, and `Another Notes App` really nails those points (I also like how it is slightly lighter than `Notally`).

Unfortunately, there are a few features missing in your app, so I shall post issues with feature requests regarding them in order to reach feature parity (and hopefully beyond that I'm the future).

Starting with, adding an option to view the created date of a note, preferably in a similar fashion to Notally, where if it is less than a day, it shows in the largest unit that has passed (hours, minutes, etc.)

For example:
Less than a day: 5 hours ago
Less than an hour: 5 minutes ago
Less than a minute: 5 seconds ago. 

And seriously, keep it up.
I can see that I am the first one to post an issue, which may or may not mean that less people are aware of your work, but hopefully it will be much more well known.

**Comment by maltaisn** [comment]
Thank you for your interest in my app. I do recall seeing Notally around, especially given the huge amount of self promotion that the author has done on Reddit continuously. Just keep in mind that popularity is not something I aim for. The Google Play Console currently shows 1 active user, which is probably me (although it might show 2 users soon). 

My goal was mostly getting up to speed with new Android development practices (MVVM, Google Material Components, Room, etc) by making an app. So development speed has been going really slowly since the initial release. The next release date is yet undetermined, it could be next month or it could be next year. I'm slowly finishing up on adding reminders to notes, then I'll look into what you suggested.

**Comment by moriel5** [comment]
Funnily enough, I found both Notally and Another Notes from the same source, IzzyOnDroid, since I regularly check for source updates with Aurora Droid (an alternative F-Droid client), one of which I enable is IzzyOnDroid.

While I do have access to Google's Play Store, that is via Aurora Store (from the same author as Aurora Droid), since I am a noGAPPS user (practically, I do make use of a few Google apps, but not anything I'd call their core apps), so I do not believe that I'll be contributing towards the Console count.

To say the truth, at first glance I thought that Another Notes was an indirect clone of Notally, since they look so similar on the surface, however after digging a bit, I saw that Another Notes's GUI was more of the functional asthetics type than Notally (there are a few points that I had asked of the author of Notally about, but he either had a different preference (the options appearing where you press vs. appearing from the bottom of the screen, something that also blocks batch operations on Notally), which is why I am so hyped about Another Notes.
The final straw for me was a few hours ago, when I discovered that he completely disabled the Issues section on his GitHub page, including removing all existing issues, since while he's a great guy, I don't understand the rationale of not allowing feedback on the project page (in my opinion, bug reporting is a form of feedback, just a more formal kind).

I understand the situation, and while I would be happy to see these features faster, I'd rather you do things at your own pace, especially since Another Notes is supposed to be more of a Proof-Of-Context.
Regardless, I'm still glad to read all of this, and I'll gladly assist however I can (my time-keeping skills are notoriously bad, with my programming skills limited to the most basic parts of HTML, currently trying to be organized enough to learn towards CCNA and CCNP exams).

**Comment by maltaisn** [comment]
Added in 3d21f92

I didn't make the relative date precision go all the way to hours though, only days, but the time is shown. So you see "Today, 12:00 AM", "5 days ago, 3:15 PM", and eventually an absolute date "2020-02-01, 23:59 PM". Creation date can be optionally shown in the preview and is always shown when editing the note.

**Comment by moriel5** [comment]
That is great!
