### ISSUE TITLE
[Feature request] Support for more link types

### ISSUE THREAD

**Issue by anedroid** [maltaisn/another-notes-app#107]
Another Notes app automatically recognizes URLs in the text and turns them into clickable links, but as of my tests only http, https and ftp URLs are being recognized, also email addresses and domain names. I would suggest to treat everything matching i.e. `\w+[-\w]*:\/[^ ]+` like an URL, because there are many different protocols other than http(s), here are some examples:

* ftps
* sftp
* ssh
* mailto
* tel
* geo
* gemini
* gopher

...and new ones may appear in the future, i.e. fedi links for the purpose of mobile apps like Tusky.

Also I noticed some special TLDs like onion, i2p or loki used in p2p networks are not recognized. I suggest add them too.

* * *

* App version: 1.5.0 F-Droid
* Android version: 12
* Android distribution: LineageOS

**Comment by maltaisn** [comment]
I'll undo this change... nobody uses these schemes anyway and more importantly the way I did it breaks a lot of things (see all the links opened). I found a way to make it all work but the amount of duplication needed is not worth it IMO.
