### ISSUE TITLE
Backup and Restore, as well as Import

### ISSUE THREAD

**Issue by moriel5** [maltaisn/another-notes-app#11]
This may be irrelevant at this point, however I can't see a way to restore a backup in Another Notes, though backing send to be working as expected.

Additionally, I wonder whether it is feasible to add support for importing backups from other note taking apps, provided they do not use a convoluted scheme.

Notally backs up it's notes to a basic XML, and can export individual notes as either plain text, HTML, or PDF (not relevant), for an example of something that can be imported.

If you are interested, I can copy the raw XML contents of a backup of two notes (one regular, one list) just for this issue (I temporarily installed Notally on this device for this).

**Comment by maltaisn** [comment]
I agree on the fact that current export feature is practically useless without import. I can probably add an import feature working with the exported data eventually. For now I'll just add a version number to the export data so it can be used in the future.

Note that your phone most likely makes automatic backup of the app's data, and you would recover them should you uninstall the app or change your phone. The backup is made with some interval, a week or so I guess.

**Comment by moriel5** [comment]
That would have been true, had I relied on GAPPS, which I do not, so no automatic backup here.

**Comment by sphh** [comment]
Does Another Notes currently store its data in the file system. Where would that be, so that we can at least make a manual backup of this directory?

**Comment by maltaisn** [comment]
@sphh The data is stored in the internal app directory, as a SQLite database, and it's unfortunately not accessible unless your phone is rooted. Data import is a planned feature, but I can't give an ETA. I don't plan how making the app database available externally, as that require an additional permission.

**Comment by sphh** [comment]
Thanks for the explanation. That's what I thought (and it is unfortunate, if you don't want to entrust your data to Google …)

**Comment by maltaisn** [comment]
I added an import feature, as well as an automatic export feature. A file can be chosen on the system to automatically export the notes every day. That should work great as a backup feature. The file can be located on the cloud, as long as it is accessible via the system.

**Comment by trizen** [comment]
The import feature doesn't work for me (Android 7.1.1). When trying to select a json file to import, all files are grayed out and cannot be selected. Maybe the app is missing the "Acess to storage" permission?

**Comment by maltaisn** [comment]
@trizen Does your file has a .json extension? Other files will appear grayed out. The storage permission is deprecated, and the Storage Access Framework used here shouldn't require it.

**Comment by trizen** [comment]
The file does have a `.json` extension. And cannot be selected.

![Screenshot_20210705-145323](https://user-images.githubusercontent.com/614513/124467704-4b895600-dd3c-11eb-8eb8-db995aa17ec6.png)

**Comment by moriel5** [comment]
I can confirm that I am facing the same exact issue as @trizen, on both Android 7.1.2 and 9.

**Comment by maltaisn** [comment]
It might be a bug of the storage access framework which doesn't support the mime type filter properly, or maybe I set it wrong. I removed the filter for now. Can you try it? Here's the APK for the latest commit on the `dev` branch: [app-debug.zip](https://github.com/maltaisn/another-notes-app/files/6794444/app-debug.zip). Alternatively you can build it yourself if you have Android Studio. It's a debug build, the app package name is different, so it will not interfere with the existing application.

**Comment by moriel5** [comment]
I have no issues importing the .json backup on the debug build, so I can confirm that the issue is purely with the mime type filter.

**Comment by trizen** [comment]
I also tested the debug app and I confirm that the import feature is working correctly.
