### ISSUE TITLE
F-Droid release not updated

### ISSUE THREAD

**Issue by smaragdus** [maltaisn/another-notes-app#110]
[F-Droid](https://f-droid.org/en/packages/com.maltaisn.notes.sync/) release is one version behind, it is still at version **1.5.0** while the latest version at [GitHub Releases](https://github.com/maltaisn/another-notes-app/releases) is [1.5.1](https://github.com/maltaisn/another-notes-app/releases/tag/v1.5.1). Any idea why F-Droid hasn't updated to the latest version of [Another notes app](https://github.com/maltaisn/another-notes-app)?

**Comment by smaragdus** [comment]
Somehow I missed #58, sorry. I am closing this issue yet F-Droid hasn't yet compiled the latest version.

**Comment by maltaisn** [comment]
Actually it should be 1.5.1, I'm not sure why it didn't get compiled...
