### ISSUE TITLE
Understanding 

### ISSUE THREAD

**Issue by shero333** [maltaisn/another-notes-app#135]
Hi, i recently review your code! and everything was fine and it runs fine too! Actually, i wanted to understand the DI you are using in the project! I will be glad if you give some time on it or provide me with a document which depicts the DI being used in the project! Just wanted to clear the concept! Will be oblidged!

**Comment by maltaisn** [comment]
Your guess is as good as mine at this point, I don't remember much except that it was a pretty standard DI setup as of 4 years ago. I think people use Dagger Hilt now on Android but I have no clue what it does.
