### ISSUE TITLE
Ability to exclude all notes inside a category from the main screen

### ISSUE THREAD

**Issue by avently** [maltaisn/another-notes-app#15]
Let's say you have thousands of notes divided into several categories (tags).
That would be impractical to have all of them displayed in a heap. In my situation I have some categories of notes that should be displayed inside main screen and another categories that should be excluded. Notes from excluded categories (hidden) can be only visible inside it's category. 

Example: you have a category named Spanish. This category has option `visible = false`.
You have some uncategorized notes on your main screen. Once you choose this category for any notes they become hidden from main screen and become available only in the category screen.

Do you like the idea?

**Comment by maltaisn** [comment]
I suppose there could be an option to hide notes with a particular labels from the main screen. For now you can label them and archive them, so that they won't appear on the main screen but they will appear when you go to the label section. They will all be visible in the archive screen though, but I guess that doesn't cause much harm.

**Comment by maltaisn** [comment]
I added an option to hide notes with a label. The option is available in the same dialog as the one used to rename a label, there's a checkbox that can be checked to hide the notes from the active (main) and archived sections. A note with a hidden label will only be shown in the label's dedicated section, the reminders section if there's a reminder on it, and the trash should the note be deleted.

**Comment by avently** [comment]
That's awesome, thanks!
