### ISSUE TITLE
Remove blank note discarded message

### ISSUE THREAD

**Issue by avently** [maltaisn/another-notes-app#16]
When I create a new note and do not write anything inside it, then pressing back button, I see a disappearing card and a message "Blank note discarded". I don't know why it can be useful. Why not to just not creating a card for a blank note and not showing the message at all?

So, I have a blank note, I'm pressing back button, i see nothing new in the main screen (no blank card, no message about blank note). It's much less intrusive behavior.

**Comment by maltaisn** [comment]
> Why not to just not creating a card for a blank note and not showing the message at all?

The editing screen has no way to discard a note except the back arrow. Creating a new blank note then deciding not to create it after all would create a blank note every time, and it would have to be deleted, which I think would be annoying. The message purpose is to clarify the discarding behavior, which might not be obvious for first time users. The message is relatively short (3 seconds or so), it's not that intrusive.

I could add an option to not discard blank notes though.

**Comment by avently** [comment]
@maltaisn so why do you create blank note first and then deleting it?
I'm saying that it would be logical to not create a note until it's not empty and than you don't need to show the discard message and inserting/removing a new card.
