### ISSUE TITLE
Export data crashes the app

### ISSUE THREAD

**Issue by MonsterSwagger** [maltaisn/another-notes-app#18]
Is this an issue specific to my device or are others are also facing it?

**Comment by maltaisn** [comment]
Thanks for the report, I fixed it. Only occurred in release mode, so the tests didn't pick it up and neither did I when I tested in debug mode!

**Comment by MonsterSwagger** [comment]
Thank you for fixing the issue so quickly and thanks for this awesome app. Can't wait for the next update.
