### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by moriel5** [maltaisn/another-notes-app#2]
It would be awesome if `Another Notes App` supported tagging notes, to view them in a more categorized way.

**Comment by frknltrk** [comment]
that would be just great! i've tried almost all note-taking apps out there and this app turned out to be the best one alternative for Google Keep. you can take a note just right away. yet only these 2 essential features are missing: Sync and Label. i'm looking forward for them.

**Comment by moriel5** [comment]
@frknltrk Sync is probably not going to come back.
More information can be seen in issue #6.

**Comment by maltaisn** [comment]
Added with 836692af..7088b0e4
