### ISSUE TITLE
Show reminder info inside notes

### ISSUE THREAD

**Issue by denthebro** [maltaisn/another-notes-app#24]
The reminder info is shown in the notes list view, but not inside the notes themselves. Please add the same reminder info badge to the note view. Currently I have to go back to the list view or go to the edit reminder modal to see the current reminder settings.

![Reminder](https://user-images.githubusercontent.com/53250435/123945221-e3074580-d9d8-11eb-980c-5044f578f0a2.jpg)

**Comment by maltaisn** [comment]
Yes this is indeed missing, I will add it.
