### ISSUE TITLE
[Feature request] implement exporting encrypted data. 

### ISSUE THREAD

**Issue by ghost** [maltaisn/another-notes-app#29]
As a user who is concerned about privacy I hope the exporting data could be encrypted.

I also have a question, is the data stored in the device are encrypted? I mean if my big-brother apps can read the unencrypted content？

Another notes is one of the best note app in Android and thank you for the consideration. 😏

**Comment by maltaisn** [comment]
> I also have a question, is the data stored in the device are encrypted? I mean if my big-brother apps can read the unencrypted content？

The app database is stored in "internal storage directories". From the [Android documentation](https://developer.android.com/training/data-storage/app-specific):

> **Internal storage directories:** These directories include both a dedicated location for storing persistent files, and another location for storing cache data. The system prevents other apps from accessing these locations, and on Android 10 (API level 29) and higher, these locations are encrypted. These characteristics make these locations a good place to store sensitive data that only your app itself can access.

As for encrypting exported notes data, it might be done should I add a password lock feature eventually, but I can't say when.

**Comment by maltaisn** [comment]
Added in v1.5.1.
