### ISSUE TITLE
RTL Layouts Support 

### ISSUE THREAD

**Issue by afmbsr** [maltaisn/another-notes-app#30]
Please support RTL languages ​​layouts.

**Comment by maltaisn** [comment]
You're right I completely overlooked it. 

I have a question for you: the app is yet to have a translation in a RTL language. I know that text in a RTL language is normally right aligned. How should English be aligned in a RTL layout? For example this dialog:

<img width="500px" src="https://user-images.githubusercontent.com/33690959/126013928-dfb10173-9875-467e-8caa-cbd760f23437.png"/>

Is the body text correctly aligned? Or would it be more natural for it to be right-aligned instead?

What about notes you would take in English. Is this right:
<img src="https://user-images.githubusercontent.com/33690959/126017023-2c63f774-6167-4fc5-b111-0a84ad529e4f.png" width="500px"/>
It feels a bit weird with the item bullets `-` not aligned.

**Comment by afmbsr** [comment]
> I have a question for you: the app is yet to have a translation in a RTL language. I know that text in a RTL language is normally right aligned. How should English be aligned in a RTL layout? For example this dialog:



> Is the body text correctly aligned? Or would it be more natural for it to be right-aligned instead?

Aligning the English text of the UI elements to the right is very normal, because the application needs translation in order for it to look correc. 

> What about notes you would take in English. Is this right:

> It feels a bit weird with the item bullets - not aligned

Also true, but not completely perfect, and to make it even better I have two ideas:

- Since the application depends on the language of the phone in the user interface, can you make the application understand this rule (if the language of the phone is an RTL language, any text is written in English only ,It has to be the alignment to the left).

- Or provide an option in the settings to center the alignment of the typed text, which is useful in all cases.

**Comment by maltaisn** [comment]
> Aligning the English text of the UI elements to the right is very normal, because the application needs translation in order for it to look correc.

No that's actually done automatically depending on the characters used. The characters determine the alignment. Currently if you type Arabic characters in a text field, they will be right-aligned, but English will be left-aligned, even in RTL layout. It's the same for a lot of the UI components.

I made a few changes, I'll let you see if it's fine. Here's the latest debug build: [app-debug.zip](https://github.com/maltaisn/another-notes-app/files/6836227/app-debug.zip), it will get installed as a separate application so you don't need to worry about losing your notes.

**Comment by afmbsr** [comment]
I did not see any change!

**Comment by maltaisn** [comment]
There should be a bunch a texts right aligned that weren't before. A few icons were mirrored too. But I left all the text fields left aligned since right alignment happens automatically when you type in a RTL language. Can you point me any additional changes required?

**Comment by afmbsr** [comment]
![٢٠٢١٠٧١٨_١٦٢٢١٢](https://user-images.githubusercontent.com/38974362/126068785-92a777a1-791b-4c53-b0af-61ed88de3140.jpg)

**Comment by maltaisn** [comment]
Ok I was using "Force RTL layout" from the developer settings so it worked for me. I changed my phone language to Arabic and indeed it doesn't work. I tweaked a setting to make it work, here's the new build: [app-debug.zip](https://github.com/maltaisn/another-notes-app/files/6836361/app-debug.zip), please let me know if it works for you and if anything is missing.

**Comment by afmbsr** [comment]
One thing left to do with the bidirectional lines,

  When a single line starts with an English word, an error occurs in text direction and alignment

![٢٠٢١٠٧١٨_١٧٢٦١٥](https://user-images.githubusercontent.com/38974362/126071244-56850c61-b056-4f6d-b70c-7677d2d5099d.jpg)


Also, when I write a paragraph and the first line begins with an English word, an error occurs in the direction of writing in the first line and an error in alignment for the entire paragraph

![٢٠٢١٠٧١٨_١٧٢٥٠٧](https://user-images.githubusercontent.com/38974362/126071275-6bd11888-4621-49c3-b4a4-6d340fdbcbe8.jpg)

**Comment by maltaisn** [comment]
Ok I think I got it, here's the latest build: [app-debug.zip](https://github.com/maltaisn/another-notes-app/files/6836563/app-debug.zip). I found an option to enter RTL editing mode if *any* RTL characters appears in the text, it appears to give the same results are you showed.

What if the line contains only English text? Should it be left aligned then?

**Comment by afmbsr** [comment]
> Ok I think I got it, here's the latest build: app-debug.zip. I found an option to enter RTL editing mode if any RTL characters appears in the text, it appears to give the same results are you showed.

Good, but it needs to be fixed in the preview card as well

![٢٠٢١٠٧١٨_٢٠٣١٢٢](https://user-images.githubusercontent.com/38974362/126077438-f5a1a4b9-09dc-4ab8-9922-cc5faef7dddf.jpg)

> What if the line contains only English text? Should it be left aligned then?

Slightly acceptable, and to make it more perfect, can you make the app understand that any text written in English only whatever the language of the phone system, should follow the left alignment, and if this is not possible how about providing the center alignment option?

![Screenshot_٢٠٢١٠٧١٨_٢٠٤٠٤٣](https://user-images.githubusercontent.com/38974362/126077494-3326b473-6a92-4a73-b0cd-01d72f639a58.png)

![Screenshot_٢٠٢١٠٧١٨_٢٠٥٤٢٥](https://user-images.githubusercontent.com/38974362/126077513-5f821469-d67c-493d-a794-7cf078b7f739.png)

**Comment by maltaisn** [comment]
If English text is left aligned, wouldn't it feel weird when you have a note in both languages? Half the items left aligned and the other half right aligned. 

I can't really detect English easily, all I can do is adjust alignment based on the presence of RTL characters. I can make it right aligned only when there's at least one RTL character in the text, the rest of the time left aligned (instead of always right aligned like the latest build). 

About center alignment, I'll think about it, but I feel like it would make the UI inconsistent.

**Comment by afmbsr** [comment]
> If English text is left aligned, wouldn't it feel weird when you have a note in both languages? Half the items left aligned and the other half right aligned

No, it is not strange, this makes the application more professional in supporting the layout of different languages

> I can make it right aligned only when there's at least one RTL character in the text, the rest of the time left aligned (instead of always right aligned like the latest build).


Can you provide me with a new build that includes this method, so that I can understand what you mean?

**Comment by maltaisn** [comment]
[app-debug.zip](https://github.com/maltaisn/another-notes-app/files/6836982/app-debug.zip)

![image](https://user-images.githubusercontent.com/33690959/126082745-f7a3089f-3021-4b14-aec7-6290834bed64.png)

**Comment by afmbsr** [comment]
Yes, these are the results I wanted to get, but I wonder do the British, French and others mix letters from RTL in their writing as well?  If the answer is “Yes”, then this build does not benefit them at all, and we have to go back to the build that preceded the current build, and if the answer is “No”, then this is very good.

**Comment by maltaisn** [comment]
> I wonder do the British, French and others mix letters from RTL in their writing as well?

I, for one, don't. I don't think I had ever typed a RTL character seriously before testing this. I think it should be fine this way.

**Comment by afmbsr** [comment]
OK, just wanted to remind you not to forget to apply changes to previews as well, thank you very much.

![٢٠٢١٠٧٢١_٠٨٥٢١٩](https://user-images.githubusercontent.com/38974362/126438320-bf2d4c12-4869-48d8-9e8f-bc11379a0f7d.jpg)

**Comment by moriel5** [comment]
I really need to find time to finish with my Hebrew translation, as that is also an RTL language.
