### ISSUE TITLE
Data import not working

### ISSUE THREAD

**Issue by kheyros** [maltaisn/another-notes-app#39]
Data import is not working, at least with Google Keep export files (json). 

When selecting a json file, the app notices me with the following message: "Une erreur est survenue en essayant de lire ce fichier" which is french for "An error occured trying to read this file".

I tried several files, all from Google Keep data export.

**Comment by maltaisn** [comment]
What do you mean by Google keep export files? The import feature only supports file generated from the app, not other apps.

**Comment by kheyros** [comment]
@maltaisn Ok sorry, it's totally my bad, I was trying several note apps found on F-Droid and was confused between yours and another one. Sorry for disturbing you for nothing.
However, it would be a great feature to implement, to make easier to your potential new users to leave Google Keep.
