### ISSUE TITLE
Note Pinning

### ISSUE THREAD

**Issue by moriel5** [maltaisn/another-notes-app#4]
It would make things easier if we could pin specific notes, leaving them always at the top.
This would be very useful in multiple situations, especially with to do notes that are meant to be for a specific time, such as a shopping list, or a note of importance that needs to be referenced very often. 

Edit: I see that you have already added this in the "Dev" branch.
Should this issue be closed, or be left open until the next release?

**Comment by maltaisn** [comment]
Yes note pinning is already implemented. I'll close it.
