### ISSUE TITLE
Multiple Enhancementa

### ISSUE THREAD

**Issue by Halfmit** [maltaisn/another-notes-app#42]
App is amazing. It has almost everything one can ask for in a Note taking app. You can change the view type in the main screen. Batch selection is there as well. Search is up there. But some things that must be added.
Feature Requests.
1. Add a custom sort option: We should be able to sort the notes as per our needs. Long press the note and move it to wherever you want it to be irrespective of it's date of creation. Top bottom middle anywhere.
2. Text editing: Needs some simple text editing features like italic and bold. That would do.
3. Picture Notes: adding pictures in notes is not bad.
4. And whatever you find suitable

**Comment by maltaisn** [comment]
> Add a custom sort option: We should be able to sort the notes as per our needs. Long press the note and move it to wherever you want it to be irrespective of it's date of creation. Top bottom middle anywhere.

I just added the sort option. As for long press to reorder, I'll consider it. I'll open a new issue to keep it in mind.

> Text editing: Needs some simple text editing features like italic and bold. That would do.

I won't add styles, see #17.

>  Picture Notes: adding pictures in notes is not bad.

See #13.

I'll close the issue since it's already covered by existing ones.
