### ISSUE TITLE
Better color UI

### ISSUE THREAD

**Issue by snxox** [maltaisn/another-notes-app#48]
Please create a better color UI
More than 10k new stars ⭐️ 
:)

**Comment by maltaisn** [comment]
Can you elaborate? I'm not sure what you mean.

**Comment by Twenty4marc** [comment]
Can you make a UI like Google Keep? 
This would be toooooo great. 
Everyone would support UI.
Only a Google keep UI 😘😍
Something like you can see in the screenshot ;)
![image](https://user-images.githubusercontent.com/84094547/133317684-c4fbaf5c-1b91-4119-b300-9b81cbfa6dd5.png)

**Comment by maltaisn** [comment]
There already an issue about colors, see #14.

If you want Google Keep UI, the best advice I can give you is to use Google Keep. The app is already heavily inspired by Google Keep, but I left out UI elements I didn't like, like their atrocious "material" theme which violate several of their own rules.

I'll close this for now, if you have specific requests please open other issues.

**Comment by Twenty4marc** [comment]
Please make a better UI and I can help you growing ✌️

**Comment by moriel5** [comment]
I agree with @maltaisn, and I personally believe that Material Design 2 pretty much ruined Material Design (and this is without even going into Google not even following their own guidelines), and while Material You has things going for it, it still doesn't solve some of the atrocities introduced with Material Design 2, especially in regards to accessibility (like where menus open).

This is part of the reason why I switched from Notally to another-notes-app, it actually sticks to a sane design which is also comfortable to use.
