### ISSUE TITLE
Import overwrites newer version of note

### ISSUE THREAD

**Issue by kumrzz** [maltaisn/another-notes-app#49]
Save a bunch of notes
Settings>Export data
amend/add to an existing note
Settings>Import data
That last action is supposed to merge, but it really just restores to prior version; which is not ideal.

Import notes should at the very least create a backup copy of any note if it already exists rather than an overwrite. Ideally an option should be thrown to user to choose etc.

**Comment by maltaisn** [comment]
Yes I admit it could be safer. Currently if the note ID and added date are the same, the note is overwritten. I could add an extra condition for the last modified date, and an option to keep all notes instead of overwriting.

**Comment by kumrzz** [comment]
Yes thanks, 'option to keep all notes instead of overwriting' or just that as default(i.e. not an option) would be a good tactical fix (also worth updating the action description to not say 'merge' if it's not really a merge - misleading).
But I think the long term fix would be to look for the timestamp : if you're only recording last mod date rather than full timestamp I feel changing that to seconds would make 'an extra condition for the last mod' watertight. Of course, if ID exists and timestamp is different, do not overwrite but create a copy instead.

**Comment by maltaisn** [comment]
> But I think the long term fix would be to look for the timestamp : if you're only recording last mod date rather than full timestamp I feel changing that to seconds would make 'an extra condition for the last mod' watertight. Of course, if ID exists and timestamp is different, do not overwrite but create a copy instead.

I'm not sure I follow. The timestamp is currently stored with milliseconds precision.

I just changed it so that notes are only overwritten if both the creation and last modification date are the same (to the millisecond). Since adding a reminder or a label doesn't change the last modified date, they are handled explicitly. Labels are merged, and if the reminders of the two notes differ, the note isn't overwritten.

Do you think that would work? It should prevent any loss of data, but it may result in more duplicated notes.

**Comment by kumrzz** [comment]
Ah sorry I misunderstood then(didn't know date = timestamp with millisecond precision)
Also didn't know this thanks : "adding a reminder or a label doesn't change the last modified date"
Still important to prevent loss of data, even if that means more dupes so yes this would work very well thanks!

I'd say long term in that case, to throw a warning or option to the user what the duplicates are and whether to selectively keep the old ones or drop them.

**Comment by maltaisn** [comment]
The changes will be available by next update. I'll let the user identify duplicates, it shouldn't be too hard usually.

**Comment by kumrzz** [comment]
That's very good, thanks for the quick turnaround and for listening! 
FWIW your competitor notally just copies everything over and over again, so this app is already better.
