### ISSUE TITLE
Input fields are cut off in landscape mode

### ISSUE THREAD

**Issue by afmbsr** [maltaisn/another-notes-app#53]
The input field in the dialog for "Create new label" and "Edit label name" is truncated when the application is used in landscape mode.

https://user-images.githubusercontent.com/38974362/140607707-eaee0828-1333-4d8d-b0fa-ca97e5760cff.mp4

**Comment by maltaisn** [comment]
There's actually a scrollbar, but that doesn't seem enough here. I'll try to find a solution. Thanks for the report.

**Comment by maltaisn** [comment]
Fixed by hiding the title when screen height is constrained:

![image](https://user-images.githubusercontent.com/33690959/146388252-dd6716ba-30fa-46c0-a80a-4c5356dc93c7.png)
