### ISSUE TITLE
Spell checking highlights are weird in the app

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [maltaisn/another-notes-app#54]
I have made an [issue](https://github.com/florisboard/florisboard/issues/1391) to Floris Board about can not getting the spell checker working on my samsung device. That has been mainly resolved but I have noticed spellchecker acts weird in this app.

This is how it goes:

I create a wall of gibberish with underldines indicating spell checker noticing that. But while writing after a while underlines start disappearing.

After exiting the app the lines are gone, unless I make another gibberish word somewhere (lets say in the middle of the words of gibberish) and press space. It gets highlighted, and If I click on it a FEW worss get highlighted BEFORE the new highlighted word.

As the following:

![image](https://i.kek.sh/lUHJuY2PCBg.jpg)

I have selected the last highlighted words and you can notice none of the other words are highlighted. If I create more the last underlines start disappearing after another. This can change from row to row depending on the last word selected. It might depend on the amount of words or letters highlighted before.

Also while writing a new word and having no space after that ALL the highlights disappear. They only reappear after adding a space after the last written word.

I'm on Android 11, OneUI 3.1, Galaxy A52s 5G, latest F-droid release.

**Comment by maltaisn** [comment]
I could not reproduce the problem. But you're not the first having issues with text editing, I'll probably have some time to look into it in December or January.

**Comment by IHateTheProgrammingClass** [comment]
Perhaps it's only Samsung devices.

**Comment by GithubContributor832** [comment]
@maltaisn thanks for all your hard work. This is a beautiful notes app with no bugs as far as I can see. I'm an open source guy and bugs usually come along with open source apps unfortuanetly. The UI is gorgeous and it's works beautifully. Thank you! I've been running it for awhile!

**Comment by IHateTheProgrammingClass** [comment]
Look I don't think this is that prevalent of a problem. I used debloater software so it's a niche problem applying probably only for me. Since the issue I have observed other text based applications doing it like this, maybe it's a feature idk. I'll close for now I don't think it's even worth looking into. Ty
