### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [maltaisn/another-notes-app#58]
https://monitor.f-droid.org/builds/log/com.maltaisn.notes.sync/10402#site-footer Could you please take a look? Thanks!

**Comment by maltaisn** [comment]
Hmm I can't reproduce it. There's not a lot of details, looks like it's an internal reflection error. Do you think we could change the build command to add `-x app:lintVitalAnalyzeRelease` to ignore that task?

**Comment by linsui** [comment]
It's possible but I don't know if it's a good idea...

**Comment by kumrzz** [comment]
so is this why we don't see the latest build in F-Droid ?

**Comment by maltaisn** [comment]
Yeah... sorry. I think it might be due to the OpenJDK 11 or Gradle 7 update. In the meantime you can download the APK [here](https://github.com/maltaisn/another-notes-app/releases/tag/v1.4.2), or build it yourself.

**Comment by linsui** [comment]
The workaround works. But we'd better find a proper fix.

**Comment by kumrzz** [comment]
I think if you were to build or install via current apk, you'd need to uninstall(inconvenient) the existing app first (if) it was installed from f-droid. This is what I got:

Failed to install: Another Notes
INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.maltaisn.notes.sync signatures do not match previously installed version; ignoring!

**Comment by AnaelMobilia** [comment]
This issue has been fixed on f-droid side on January 2022, so the issue could be closed :-)
=> https://gitlab.com/fdroid/fdroiddata/-/commit/bfe29e97367fc17346fd7c1c1a9e08ff0b19cd56#0d44044f5a8534a743dee2ccf9d3dffb9d035c1a

Bests regards,
Anael

**Comment by maltaisn** [comment]
Thanks!

**Comment by smaragdus** [comment]
@AnaelMobilia & @linsui

Any news on F-Droid end? Is it still unable to compile the latest version, [1.5.1](https://github.com/maltaisn/another-notes-app/releases/tag/v1.5.1)?

**Comment by linsui** [comment]
It's not picked because the  build.gradle files was changed... Fixed.

**Comment by smaragdus** [comment]
@linsui 

Thanks!

**Comment by smaragdus** [comment]
@linsui The latest version is live on F-Droid, thanks.
