### ISSUE TITLE
Future Recommendation For Synchronization

### ISSUE THREAD

**Issue by moriel5** [maltaisn/another-notes-app#6]
I see that you used to have synchronization as a feature.

How about adding support for NextCloud and OwnCloud in the future?
That way, the user could add their own personal servers ("clouds").

**Comment by maltaisn** [comment]
Yes there used to be a synchronization feature. The rationale for removing it is explained [here](https://github.com/maltaisn/another-notes-app/blob/sync/README.md#synchronization). Mostly I just didn't want to rely on a third party service. I have currently no plans in adding it back in any way. Auto-backup perhaps, but I feel like synchronization is really too much of a hassle.

**Comment by moriel5** [comment]
Yeah, I read those and I fully agree, I had just thought of dropping this suggesting in case you may like them.

Auto-backup is a great alternative, especially if the user could restore directly from the server (though I personally would prefer doing that via the system file manager).

**Comment by Hund** [comment]
What about saving the files as pain text files? Then any user can choose where to save them and use whatever way of syncing things they want.

**Comment by carallo** [comment]
> What about saving the files as pain text files? Then any user can choose where to save them and use whatever way of syncing things they want.

I agree, if notes could be exported in .txt or .md files they could be synced through Nextcloud but you wouldn't need to take care of the development of any sync feature. Actually if it would be possible even to select the folder where notes are saved, it would be even easier (selecting the Nextcloud folder through the stock file manager).

**Comment by kumrzz** [comment]
The app currently offers an export as json (settings >export data),and an auto data export. I just use syncthing (why use a cloud service which someone else controls?) to sync those files across devices.

**Comment by carallo** [comment]
> The app currently offers an export as json (settings >export data),and an auto data export. I just use syncthing (why use a cloud service which someone else controls?) to sync those files across devices.

But how can you open it on the desktop then?

**Comment by kumrzz** [comment]
json is a common standard, plenty of json editor apps available online/to download. Syncthing is just one app (which btw is also available on Windows etc)
Note the data is still viewable in a text editor, just with a bunch of json formatting.

**Comment by carallo** [comment]
> json is a common standard, plenty of json editor apps available online/to download. Syncthing is just one app (which btw is also available on Windows etc) to share across devices.
> Note the data is still viewable in a text editor, just with a bunch of json formatting.

Oh yes I know, I was referring to which app can you use that picks up the _Another Notes App_ json formatting. I think that's the main issue here with syncing. I can sync across other android devices with autobackup to a synced folder that gets picked up from the other device with _Another Notes App_ installed. But using a more standard format would allow people to sync to other platforms as well, and in general to use other notes apps that use the same standard format.

**Comment by kumrzz** [comment]
Ah sorry I misunderstood then, I only sync across android devices using the same app so inter app compatibility hasn't been an issue for me.
I feel this now raises the question what's really the "standard format" for notes apps, I see the dev here decided on json and that'd be my preference too since it preserves formatting that text might lack. But sure, this is an interesting topic :)

**Comment by carallo** [comment]
> Ah sorry I misunderstood then, I only sync across android devices using the same app so inter app compatibility hasn't been an issue for me.
> I feel this now raises the question what's really the "standard format" for notes apps, I see the dev here decided on json and that'd be my preference too since it preserves formatting that text might lack. But sure, this is an interesting topic :)

Well yes, probably that's the right question! 
I agree that json is a pretty good and accessible format, the only issue is that each app uses different json formats, which in the end does not allow cross compatibility among apps, correct me if I'm wrong. Maybe markup could be a compromise? I see it's pretty common nowadays in note apps. But yes, it's hard to find a "standard" format for notes today, but I think such direction should be taken, at least by FOSS apps.
