### ISSUE TITLE
App crashes after trying to set reminder

### ISSUE THREAD

**Issue by jeremiah-miller** [maltaisn/another-notes-app#62]
I tried to set a reminder on a list and the app crashed when i hit ok, and it crashes everytime i try to launch the app. I tried clearing the app cache but that didn't work, it still crashes. I think the note may not have had a title but i'm not sure. On android 12

**Comment by atomwaffel** [comment]
I have the exact same problem since upgrading to Android 12.

**Comment by maltaisn** [comment]
Thanks for the report and sorry for the inconvenience. I think this is the same as #61.
Can you test this APK and check if the bug still occurs? [app-debug.zip](https://github.com/maltaisn/another-notes-app/files/7963983/app-debug.zip)
I don't have Android 12 and I'm having issues with emulator, I'd like to release the fix as soon as possible.

**Comment by atomwaffel** [comment]
> Thanks for the report and sorry for the inconvenience. I think this is the same as #61. Can you test this APK and check if the bug still occurs? [app-debug.zip](https://github.com/maltaisn/another-notes-app/files/7963983/app-debug.zip) (it's the debug build, it will install as a separate app) I don't have Android 12 and I'm having issues with emulator, I'd like to release the fix as soon as possible.

It just says that it couldn't parse the package...

**Comment by maltaisn** [comment]
> It just says that it couldn't parse the package...

Hmm, I think I might have to sign it... can you try this one: [app-debug.zip](https://github.com/maltaisn/another-notes-app/files/7964152/app-debug.zip)

**Comment by jeremiah-miller** [comment]
Same problem

**Comment by maltaisn** [comment]
Can you install this app https://f-droid.org/packages/taco.scoop to send be the crash report?

**Comment by maltaisn** [comment]
Here's another one: [app-release.zip](https://github.com/maltaisn/another-notes-app/files/7964287/app-release.zip). If that doesn't work, I'm clueless. Did you disable google play protect & allow unknown sources? When installing the APK it should not say that it's updating anything, just that it's installing a new app.

**Comment by jeremiah-miller** [comment]
The app-release seems to work fine, i set a reminder on a totally empty list and it worked fine. In a few minutes I'll try out other types like a list with no title, a titled but empty list, list+title, and all the same stuff but a note instead of a list

**Comment by maltaisn** [comment]
Ok well I'll consider this fixed then. The crash was due an obscure argument value suddenly becoming a requirement as of Android 12, and if that value wasn't used, it crashed the app... thanks Google.
