### ISSUE TITLE
New Bugs

### ISSUE THREAD

**Issue by techybrows** [maltaisn/another-notes-app#63]
Automatically going to the end of Note again and again. Not able to write anything in 1.4.2 and 1.4.3 updates.

Undo and Redo is really required.

**Comment by dmint789** [comment]
Yes, please fix this, almost every time I scroll through the note, it jumps to the end of the note, and this only started happening since the new update

**Comment by kumrzz** [comment]
Same, this is particularly annoying and dangerous because sometimes autocorrect kicks in and completely changes the content at that point when it snaps to the end

**Comment by maltaisn** [comment]
This should be fixed in v1.4.4, the version should be available on F-Droid during next week. Let me know if it works.

**Comment by dmint789** [comment]
I believe this is fixed based on some quick tests
