### ISSUE TITLE
Keyboard cursor controls don't work 

### ISSUE THREAD

**Issue by jeremiah-miller** [maltaisn/another-notes-app#67]
Florisboard has buttons and swipe gestures to move the cursor, but when i try to use them nothing happens. It works fine in other apps, this is the only one that doesn't seem to work. Let me know if you need any other information

**Comment by maltaisn** [comment]
By default text fields accept arrow keys, but if you want links to become clickable as you write them, you need to change that default behavior for another, losing arrow key movement in the process... I tried to merge both functionalities but I may have broken other things.
