### ISSUE TITLE
[Minor Suggestion] Make the date format more friendly to users of the DD/MM/YYYY format

### ISSUE THREAD

**Issue by dmint789** [maltaisn/another-notes-app#69]
The date is currently shown in the format MM/DD/YYYY. This can cause confusion for users of the more common DD/MM/YYYY format. I would suggest using the unambiguous DD Month YYYY format (e.g. 8 July 2022), which is understandable to everyone, although it does require the use of an English word. Alternatively, there could be an option in the settings that lets users select the DD/MM/YYYY format like in Google keep.

**Comment by maltaisn** [comment]
The date format depends on your device locale. There may be some system setting but I didn't find it. I see "Fri., Jul. 29" for example.

**Comment by dmint789** [comment]
Oh, I see. I think this is because my system language is set to American English. Could you please make the date format configurable in the app's settings, because I don't want to change my system language.

**Comment by moon-cacke** [comment]
First thanks for your amazing app :) 

Same issue here... can you please add an option to specify the format.
Thanks

**Comment by dd-dreams** [comment]
I'll work on it.

**Comment by dmint789** [comment]
Since this issue was opened the date format was changed to display the month as a word. This can probably be closed now.

**Comment by dd-dreams** [comment]
Yeah only after I implemented the toggle I saw it actually uses the month.
