### ISSUE TITLE
F-Droid Inclusion

### ISSUE THREAD

**Issue by moriel5** [maltaisn/another-notes-app#7]
Might you be interested in adding `Another Notes App` to F-Droid?
This might assist in getting your app a bit more limelight (though IzzyOnDroid's repo is already helping on that front).

**Comment by maltaisn** [comment]
See https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6681

The next release should be available on F-Droid.

**Comment by moriel5** [comment]
That's awesome, thanks for that (and I see that Izzy also was part of it).
