### ISSUE TITLE
IzzyOnDroid Banner

### ISSUE THREAD

**Issue by moriel5** [maltaisn/another-notes-app#8]
Not required, however since I have seen quite a few apps hosting such a banner on their README pages, I thought that you might also be interested in adding one.

**Comment by maltaisn** [comment]
I didn't about IzzyOnDroid, I see the app seems to be in their database. But I'm not a fan of banners and I don't think it would add much. Thanks for the suggestion anyway.

**Comment by moriel5** [comment]
No problem.
I thought that you may be interested, since you already have banners for the Play Store and the GitHub releases.

**Comment by maltaisn** [comment]
Oh I misunderstood I thought you were talking about badges. But since there's going to be an F-Droid button eventually I don't want it to become too crowded. Isn't IzzyOnDroid only some kind of mirror? Or do they also provide the download?

**Comment by moriel5** [comment]
IzzyOnDroid is an alternative application source to F-Droid, however I believe that Izzy will remove Another Notes once it goes live in F-Droid, since he usually does that to prevent duplication of efforts.
