### ISSUE TITLE
When creating a new note, focus on title

### ISSUE THREAD

**Issue by mikeyhew** [maltaisn/another-notes-app#84]
When I click on the `+` on the bottom right of the screen to make a new note, the cursor is focused on the body of the note instead of the title. This may be desired by people who want to ignore the title and make notes without one, but if you are like me and start with writing the title before getting to the body of the note, it's annoying to have to select the title field before typing the title of the note.

I suggest that when creating a new note, the title be in focus on the new note page, with possibly a setting to revert back to the current behaviour if people want that. (On the other hand, when opening an existing note, it makes total sense for the focus to be on the body and not the title, since that's likely what you want to edit.)

**Comment by maltaisn** [comment]
Makes sense. I always use a title too.
