### ISSUE TITLE
[Discussion] Material 3 Redesign

### ISSUE THREAD

**Issue by nhoeher** [maltaisn/another-notes-app#85]
# Why change anything?
Feature-wise this app is still great in my opinion. It does everything I need it to do and nothing more. Where the app starts to show its age is design-wise. It implements the original Material Design guidelines, but with more and more apps adapting Google's Material 3 Design, it looks a bit out of place on a modern Android device.

# Proposed Changes
Over the past month I have been working on a complete redesign of the app, which adheres to [Material 3 guidelines](https://m3.material.io/) and supports modern features like [Dynamic Color](https://m3.material.io/styles/color/dynamic-color/overview) (Material You). There haven't been any major architectural changes and feature-wise everything remains just the same as before.

The colors within the app dynamically adapt to the users system theme on Android 12 and above.

<img alt="Screenshot 1"
     src="https://user-images.githubusercontent.com/39745929/200121634-3b2f5cab-91a6-44f3-be1c-0ca5ccf789e0.png"
     width="30%"/>    <img alt="Screenshot 2"
     src="https://user-images.githubusercontent.com/39745929/200121734-10d4b2df-523a-4291-9511-fa7475a3bb51.png"
     width="30%"/>

Additionally shared element transitions have been added when creating or opening / closing notes and fragment transitions when navigating between different destinations. This helps to increase the overall smoothness of the UI.

The navigation drawer is one area in particular that has received a large update, to bring the look and feel more in line with what other modern apps offer.

<img alt="Screenshot 3"
     src="https://user-images.githubusercontent.com/39745929/200123217-b34a30d9-ff40-421d-8d7b-fbdc3fa969c9.png"
     width="30%"/>   <img alt="Screenshot 4"
     src="https://user-images.githubusercontent.com/39745929/200123259-394c1934-842e-4e27-af44-5e00cd38a0d3.png"
     width="30%"/>

The other fragments remain largely unchanged with only minor updates to reflect the new design language.
<img alt="Screenshot 5"
     src="https://user-images.githubusercontent.com/39745929/200123374-ed6fc6d1-c86d-48c1-a565-329b2018698e.png"
     width="30%"/>  <img alt="Screenshot 6"
     src="https://user-images.githubusercontent.com/39745929/200123540-196e5d2d-feff-4241-817b-550feac8907b.png"
     width="30%"/>
     
# What next?
All changes are complete and to my knowledge fully functional. Unit Tests run without any problems. The changes to the code can be found [here](https://github.com/nhoeher/another-notes-app/tree/feat-material3). I followed the existing coding style as closely as possible and the code should be quite clean.

## Now the big question to @maltaisn:
Would you be interested in merging these changes in some form? I know that you aren't actively developing this app anymore and since it is probably going to take you some time to look through the changes, I could totally understand if you weren't willing to do so. In that case I am most likely going to maintain my own fork and work on development there.

A response from you would be greatly appreciated. :)

**Comment by maltaisn** [comment]
Yes I can take a look at it and merge it over the next week.
